<?php
// +----------------------------------------------------------------------
// | Time  : 15:40  2018/8/31/031
// +----------------------------------------------------------------------
// | Author: whlphper  备注:
// +----------------------------------------------------------------------
namespace app\manager\controller\shop;
use app\manager\controller\shop\ShopBase;
class Category extends ShopBase{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->theme = '分类';
        $this->model = model('ShopCategory');
        $this->field = 'a.*,b.path,c.name as parent_name';
        $this->con = [];
        $this->join = [['system_file b','a.posters = b.id','left'],['shop_category c','a.parent_id = c.id','left']];
    }

    public function index()
    {
        // 获取所有分类
        $list = $this->model->field('id,name,parent_id')->select();
        $list = getSubs($list,'parent_id');
        array_unshift($list,['id'=>0,'name'=>'顶级分类','parent_id'=>0]);
        return view('',['cates'=>$list]);
    }


}