<?php
// +----------------------------------------------------------------------
// | IUBO    PHP
// +----------------------------------------------------------------------
// | Time  : 16:27  2018/9/6/006
// +----------------------------------------------------------------------
// | Author: whlphper  备注:
// +----------------------------------------------------------------------
namespace app\manager\controller\shop;
use app\manager\controller\ManagerBase;
class Help extends ManagerBase{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->theme = '帮助中心';
        $this->model = model('ShopCatelog');
        $this->field = 'a.id,a.parent_id,a.title,a.content,b.title as parent_title';
        $this->con = [];
        $this->join = [['shop_catelog b','a.parent_id = b.id','left']];
    }

    public function index()
    {
        // 获取所有分类
        $list = $this->model->field('id,title as name,parent_id')->where('parent_id',0)->select();
        $list = getSubs($list,'parent_id');
        array_unshift($list,['id'=>0,'name'=>'顶级分类','parent_id'=>0]);
        return view('',['cates'=>$list]);
    }
}