<?php
// +----------------------------------------------------------------------
// | IUBO    PHP
// +----------------------------------------------------------------------
// | Time  : 16:07  2018/9/6/006
// +----------------------------------------------------------------------
// | Author: whlphper  备注:
// +----------------------------------------------------------------------
namespace app\manager\controller\shop;
use app\manager\controller\ManagerBase;
class Member extends ManagerBase{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->theme = '会员';
        $this->model = model('ShopMembers');
        $this->field = 'a.*';
        $this->con = [];
        $this->join = [];
    }

    public function index()
    {
        return view('');
    }
}