<?php
// +----------------------------------------------------------------------
// | IUBO    PHP
// +----------------------------------------------------------------------
// | Time  : 16:07  2018/9/6/006
// +----------------------------------------------------------------------
// | Author: whlphper  备注:
// +----------------------------------------------------------------------
namespace app\manager\controller\shop;
use app\manager\controller\ManagerBase;
class Order extends ManagerBase
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->theme = '订单';
        $this->model = model('ShopOrder');
        $this->field = 'a.id,a.order_no,a.order_amount,a.desc,a.pay_type,a.status,a.progress,a.express_id,a.express_code,a.create_time,b.nick_name as user_name';
        $this->con = [];
        $this->join = [['shop_members b', 'a.user_id = b.id', 'left']];
        $this->models['member'] = model('ShopMembers');
    }

    public function index()
    {
        // 用户列表
        $user = $this->models['member']->field('id,nick_name')->select()->toArray();
        return view('', ['user' => $user]);
    }

    public function detail()
    {
        $id = input("id");
        $info = $this->model->detail($id);
        return view('',['detail'=>$info]);
    }
}