<?php
// +----------------------------------------------------------------------
// | IUBO    PHP
// +----------------------------------------------------------------------
// | Time  : 17:59  2018/9/6/006
// +----------------------------------------------------------------------
// | Author: whlphper  备注:
// +----------------------------------------------------------------------
namespace app\manager\controller\blog;
use app\manager\controller\ManagerBase;

class Article extends ManagerBase{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->theme = '文章';
        $this->model = model('BlogArticle');
        $this->field = 'a.*,b.path as poster_path,c.name as cate_name';
        $this->con = [];
        $this->join = [['system_file b','a.poster = b.id','left'],['blog_category c','a.category_id = c.id','left']];
    }

    public function index()
    {
        // 获取所有分类
        $list = model('BlogCategory')->field('id as nodeId,name as text,parent_id')->select()->toArray();
        $tree = list_to_tree($list,'nodeId','parent_id','nodes');
        $list = getSubs($list,'parent_id','nodeId','text');
        return view('',['cates'=>$list,'tree'=>$tree]);
    }
}