<?php
// +----------------------------------------------------------------------
// | IUBO    PHP
// +----------------------------------------------------------------------
// | Time  : 17:58  2018/9/6/006
// +----------------------------------------------------------------------
// | Author: whlphper  备注:
// +----------------------------------------------------------------------
namespace app\manager\controller\blog;
use app\manager\controller\ManagerBase;

class Category extends ManagerBase{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->theme = '文章分类';
        $this->model = model('BlogCategory');
        $this->field = 'a.*,b.path as poster_path,c.name as parent_name';
        $this->con = [];
        $this->join = [['system_file b','a.poster = b.id','left'],['blog_category c','a.parent_id = c.id','left']];
    }

    public function index()
    {
        // 获取所有分类
        $list = $this->model->field('id,name,parent_id')->select();
        $list = getSubs($list,'parent_id');
        return view('',['cates'=>$list]);
    }
}